const IMAGE_ALTERNATIVE_TEXT = [
  "Enable 2-Tap User Logins with 'Login With WhatsApp' for Free!",
  "Add 'Login with WhatsApp' Button for a frictionless and secure user login experience.",
  "Integrate Simple and Secure Login with WhatsApp button on your app or website",
  "Login your users without OTPs for free",
  "Remove OTPs and Passwords from your Login Page. Add Login With WhatsApp Button",
  "Use WhatsApp to provide 2-Tap Login Experience with OTPless",
  "Add Login with WhatsApp Button",
  "Bring SMS OTP cost to ZERO",
  "Prevent Account Takeovers",
  "Increase Conversion by 25%",
  "Reduce Login Drop-offs by 25%",
  "Eliminate OTPs and Passwords.",
  "Plug and Play Integration.",
  "Go Live under 30 Mins",
  "Enable 2FA Authentication",
  "Enable MFA Authentication",
  "Passwordless Authentication",
  "Enable OTPless Authentication",
  "Free Forever. Integrate Now",
  "Free Forever. Sign Up Now!",
  "Add Login with WhatsApp Button on your app or website for Free.",
];

export default IMAGE_ALTERNATIVE_TEXT;
